### ISSUE TITLE
[Stub] Fill in GDG Wisdom History in [Introduction] > What is GDG Wisdom

### ISSUE THREAD

**Issue by nitya** [gdg-wisdom/wisdom-2015#4]
```
This is the format I am proposing for creating "stubs" in the GitBook documents. 
[Stub]  <description of text required> [Chapter] > SubChapter.

Once the issue is created, we can now have a link that can be inserted into the GitBook text itself (linking to issue) so that folks can go ahead, replace it and close the issue accordingly.
```

This specific issue relates to creating text around the image showing the first GDG Wisdom team. And giving some context for the history of the project

**Comment by friedger** [comment]
Not sure about stubs in the gitbook document. I think it is good for the start, but once with have a first version out we should be able to publish a new version without waiting for all stubs to be removed, so that we can be kind of "agile" with publishing.

**Comment by nitya** [comment]
You make a great point. I agree. Okay we leave stubs out of the GitBook docs.

Perhaps we can create issues for stubs and in the issue desc point to where we want that content filled. But the published book stays clean.

**Comment by nitya** [comment]
Removing the need for stubs -- now that there is an edit-link approach, we can do this more organically. Will remove all "content stub" elements and close out the issues.
